import Cola as co
cola_1 = co.Cola()
cola_1.encolar(2)
cola_1.encolar(3)
cola_1.encolar(4)
cola_1.encolar(5)
cola_1.encolar(6)
cola_1.encolar(7)
cola_1.encolar(8)
cola_1.mover_al_frente(6)
cola_1.ver_cola()